# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "Cube4Life"
include-after = ["after.cmake"]

[fetch-content]
gtest = { git = "https://github.com/google/googletest", tag = "v1.14.0" }

[target.Cube4Life]
type = "executable"
sources = ["src/Cube4Life/*.cpp"]
compile-features = ["cxx_std_17"]
link-libraries = ["gtest", "Vulkan::Vulkan", "glfw"]
